sudo: false
language: python

dist: xenial

python:
  - "3.7"
  - "3.6"
  - "3.5"

install:
  - pip install .
  - pip install -r requirements-tests-py3.txt

script:
  - ./tests/mypy_test.py
  - MYPY_TEST_PREFIX=$PWD MYPYPATH=$PWD/third_party/3 pytest
